server:
  address: 8081

spring:
  application:
    name: Bank_System
  datasource:
    url: jdbc:postgresql://localhost:5432/db_bank
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver